name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: "이슈"
body:
  - type: markdown
    attributes:
      value: |
          새로운 기능에 대해서 설명해주세요.
  - type: textarea
    id: context
    attributes:
      label: 기능
      description: 어떤 기능인가요?
    validations:
      required: false
body:
  - type: markdown
    attributes:
      value: |
          이슈를 작성해 주세요.
  - type: textarea
    id: context
    attributes:
      label: 이슈
      description: 어떤 이슈인가요?
    validations:
      required: false
