name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: "기능"
body:
  - type: textarea
    id: overview
    attributes:
      label: ---Overview---
      description: 어떤 기능인가요?
    validations:
      required: false
  - type: textarea
    id: Screenshot
    attributes:
      label: ---Screenshot---
      description: 스크린샷이 있나요?
    validations:
      required: false
  - type: textarea
    id: Links
    attributes:
      label: ---Links---
      description: 링크가 있는가요?
    validations:
      required: false
