name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
label: "기능"
body:
  - type: textarea
    id: context
    attributes:
      label: 기능
      description: 어떤 기능인가요?
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: 이슈
      description: 어떤 이슈인가요?
    validations:
      required: false
